### ISSUE TITLE
运行app.py时报错

### ISSUE THREAD

**Issue by lanyinnow** [lsq960124/Flask-BookRecommend-Mysql#4]
<img width="1223" alt="图片" src="https://user-images.githubusercontent.com/13848580/158039562-d1ff62b4-87f1-4bf0-a249-99e52b401551.png">
作者您好 最近在复现这个项目 但遇到了一个bug 大家有遇到这个问题的么 在执行app.py时报错

**Comment by lsq960124** [comment]
【版本升级导致的】将原有的utils中的yaml.load 修改为yaml.safe_load

**Comment by lanyinnow** [comment]
> 【版本升级导致的】将原有的utils中的yaml.load 修改为yaml.safe_load

好的好的 非常感谢
